<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Theme tester tool
 *
 * @package   tool_themetester
 * @copyright  2012 Simon Coggins
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

/**
 * Returns the HTML source generated by executing the file provided
 *
 * @param string $filename Name of the file to display
 * @return HTML source code produced by the code in $filename
 */
function get_source_output($filename) {
    // we don't know what globals the file might need
    global $OUTPUT, $USER, $SESSION, $DB, $CFG;
    if (!file_exists($filename)) {
        return false;
    }
    ob_start();
    include($filename);
    return htmlentities(ob_get_clean());
}

/**
 * Returns the code contained within the file provided, escaped so
 * as to be suitable for printing to an HTML page
 *
 * @param string $filename Name of the file
 * @return Escaped copy of the code in $filename
 */
function get_html_output($filename) {
    if (!file_exists($filename)) {
        return false;
    }
    return htmlentities(file_get_contents($filename));
}

